### ISSUE TITLE
您好！请问论文什么时候公布呢？想拜读一下

### ISSUE THREAD

**Issue by HDUyiming** [zhangyin1996/ISP-Teacher#1]

**Comment by zhangyin1996** [comment]
您好，AAAI的论文官方一般会在6月公布

**Comment by zhangyin1996** [comment]
@HDUyiming 您好，AAAI的论文官方一般6月份公布

**Comment by HDUyiming** [comment]
> 您好，AAAI的论文官方一般会在6月公布

好的，谢谢，因为这个Day2Night的方向在DAOD上做的比较少，所以想着看一下，您会使用什么样的数据集去比较性能（BDDK SIM10K SHIFT?）

**Comment by zhangyin1996** [comment]
> > 您好，AAAI的论文官方一般会在6月公布
> 
> 好的，谢谢，因为这个Day2Night的方向在DAOD上做的比较少，所以想着看一下，您会使用什么样的数据集去比较性能（BDDK SIM10K SHIFT?）

BDD100k和SHIFT，在CVPR2023 2pcnet的基础上做的工作

**Comment by HDUyiming** [comment]
> > > 您好，AAAI的论文官方一般会在6月公布
> > 
> > 
> > 好的，谢谢，因为这个Day2Night的方向在DAOD上做的比较少，所以想着看一下，您会使用什么样的数据集去比较性能（BDDK SIM10K SHIFT?）
> 
> BDD100k和SHIFT，在CVPR2023 2pcnet的基础上做的工作

谢谢哈~，那我就等着论文公布再拜读您的工作，祝您工作顺利、生活愉快~

**Comment by zhangyin1996** [comment]
@HDUyiming 不客气~你可以先复现一下2pcnet
