### ISSUE TITLE
请问什么时候上传ISP-Teacher的代码呀？期待复现

### ISSUE THREAD

**Issue by HDUyiming** [zhangyin1996/ISP-Teacher#2]

**Comment by zhangyin1996** [comment]
代码已于2024/3/29上传

**Comment by HDUyiming** [comment]
> 代码已于2024/3/29上传

我发现yaml文件和trainer.py与2PCNet比较相似，没有找到具体涉及到ISP-Teacher的代码部分

**Comment by zhangyin1996** [comment]
@HDUyiming twophase/data/low_degrade.py

**Comment by HDUyiming** [comment]
感谢师兄！

**Comment by HDUyiming** [comment]
> @HDUyiming twophase/data/low_degrade.py

感谢师兄指点！
