### ISSUE TITLE
Problems in the process of replicating code

### ISSUE THREAD

**Issue by HDUyiming** [zhangyin1996/ISP-Teacher#4]
学长您好，我在复现这篇文章时遇到了些问题，首先我看您的代码并没有去掉2pcnet中的STUDENT_SCALE缩放策略和2pc一致性损失，请问您论文中汇报的结果是去除掉这些之后的吗？
我现在在没有改变任何代码的情况下，仅调整了bs=6用两张卡来复现，但是到了4.6W仍然在46.X左右浮动（SHIFT数据集）请问是什么情况呢？
（复现的细节是一开始burn in阶段是bs=12 用两张卡，到了师生互学阶段发现爆显存了，就bs=6也是两张卡来跑的）
以下是我的日志，您看一下：
[log.txt](https://github.com/zhangyin1996/ISP-Teacher/files/15501089/log.txt)
感谢您为DAOD社区带来的宝贵开源项目😀！期待您的尽早回复！

**Comment by zhangyin1996** [comment]
@HDUyiming 
感谢您对本工作的关注。
1. 本工作是基于2pcnet上进行改进的，2pcnet中的STUDENT_SCALE缩放策略和2pc一致性损失并没有改动，所以实验结果是没有去除掉这些的；
2. 通常，缩小bs是需要同时减小lr的。所以还是建议使用4张24GB的卡进行复现；
3. 此外，我当时在SHIFT上复现2pcnet时，结果波动也很大。你也可以修改lr之后，多复现几次；
4. 而2pcnet在BDD100k数据集上的结果基本是稳定的，这也是为什么我的消融实验都是在BDD100k上进行的。

如果论文对你有帮助，还请麻烦给github点一个star~

**Comment by HDUyiming** [comment]
> @HDUyiming 感谢您对本工作的关注。
> 
> 1. 本工作是基于2pcnet上进行改进的，2pcnet中的STUDENT_SCALE缩放策略和2pc一致性损失并没有改动，所以实验结果是没有去除掉这些的；
> 2. 通常，缩小bs是需要同时减小lr的。所以还是建议使用4张24GB的卡进行复现；
> 3. 此外，我当时在SHIFT上复现2pcnet时，结果波动也很大。你也可以修改lr之后，多复现几次；
> 4. 而2pcnet在BDD100k数据集上的结果基本是稳定的，这也是为什么我的消融实验都是在BDD100k上进行的。
> 
> 如果论文对你有帮助，还请麻烦给github点一个star~

谢谢，我再尝试进一步复现结果，小星星已经献上了~😊

**Comment by wuxiaofenghehe** [comment]
> > @HDUyiming 感谢您对本工作的关注。
> > 
> > 1. 本工作是基于2pcnet上进行改进的，2pcnet中的STUDENT_SCALE缩放策略和2pc一致性损失并没有改动，所以实验结果是没有去除掉这些的；
> > 2. 通常，缩小bs是需要同时减小lr的。所以还是建议使用4张24GB的卡进行复现；
> > 3. 此外，我当时在SHIFT上复现2pcnet时，结果波动也很大。你也可以修改lr之后，多复现几次；
> > 4. 而2pcnet在BDD100k数据集上的结果基本是稳定的，这也是为什么我的消融实验都是在BDD100k上进行的。
> > 
> > 如果论文对你有帮助，还请麻烦给github点一个star~
> 
> 谢谢，我再尝试进一步复现结果，小星星已经献上了~
你好，请问一下，那个shift数据集你具体是下载的那一个，官网上有很多种，谢谢你的回复

**Comment by wuxiaofenghehe** [comment]
> > @HDUyiming 感谢您对本工作的关注。
> > 
> > 1. 本工作是基于2pcnet上进行改进的，2pcnet中的STUDENT_SCALE缩放策略和2pc一致性损失并没有改动，所以实验结果是没有去除掉这些的；
> > 2. 通常，缩小bs是需要同时减小lr的。所以还是建议使用4张24GB的卡进行复现；
> > 3. 此外，我当时在SHIFT上复现2pcnet时，结果波动也很大。你也可以修改lr之后，多复现几次；
> > 4. 而2pcnet在BDD100k数据集上的结果基本是稳定的，这也是为什么我的消融实验都是在BDD100k上进行的。
> > 
> > 如果论文对你有帮助，还请麻烦给github点一个star~
> 
> 谢谢，我再尝试进一步复现结果，小星星已经献上了~😊

你好，请问以下你的shift数据集具体是下载的那一个，我看官网有很多数据集
