### ISSUE TITLE
如何通过测试或训练得到每个类别的AP50性能？

### ISSUE THREAD

**Issue by HDUyiming** [zhangyin1996/ISP-Teacher#5]
![image](https://github.com/user-attachments/assets/5d0bcef8-8440-45c9-949b-c66a07b8f5f1)
请问如何获得每个类别的AP50呀？日常训练的日志文件或测试程序中我们只能得到AP AP50 AP75以及AP大中小的物体性能，即使查看tensorboard也只能得到每个类别的AP值，但是一般我们论文中汇报的各个类别的AP50要如何获取呀？

**Comment by zhangyin1996** [comment]
@HDUyiming 
我是参考这个链接，测试时使用。
https://blog.csdn.net/qq_37541097/article/details/112248194

**Comment by HDUyiming** [comment]
谢谢师兄，但是弄了两天还是打印不出来，能麻烦你将这个测试文件发给我吗？这个测试文件需要替换到目录的哪里呢？

**Comment by HDUyiming** [comment]
谢谢师兄，我这几天试了一下还是不太行~，能否提供一下你的测试代码呀/(ㄒoㄒ)/~~？

**Comment by zhangyin1996** [comment]
@HDUyiming 
最近在放暑假，没有在学校，我可以在下周开学的时候把代码发给你

**Comment by HDUyiming** [comment]
> @HDUyiming 最近在放暑假，没有在学校，我可以在下周开学的时候把代码发给你

好的好的，谢谢师兄啦，祝师兄暑假愉快hhhh

**Comment by HDUyiming** [comment]
> > @HDUyiming 最近在放暑假，没有在学校，我可以在下周开学的时候把代码发给你
> 
> 好的好的，谢谢师兄啦，祝师兄暑假愉快hhhh

我已经找到解决办法了，2PCNet中**coco_evaluation.py**有一段`results.update({"AP50-" + name: ap for name, ap in results_per_category_AP50})`给注释掉了，取消注释就可以了

**Comment by zhangyin1996** [comment]
@HDUyiming 
我刚才测试了一下，在我的代码里取消注释那段好像不太行。我是在detectron2内部的pycocotools/cocoeval.py文件中修改的。
不过很高兴你能找到解决办法，同时告诉给了我，谢谢~

**Comment by HDUyiming** [comment]
嘿嘿，不客气~
