### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by yanguo-lucky** [zhangyin1996/ISP-Teacher#6]
Hello, how are the visualization results generated?

**Comment by zhangyin1996** [comment]
@yanguo-lucky
Hi, thank you for your interest in our work.  I have upload the visualization code in this link:
[Baiduyu](https://pan.baidu.com/s/1ui4t7kf2otWXh6kKdViSzQ) (password:6666) or [GoogleDrive](https://drive.google.com/drive/folders/1g5WsGAL0zduyXJyNucZnltyWcMSRoyHm?usp=drive_link)

1. You could download the weight of ours (48.8 AP) from [Baiduyun](https://pan.baidu.com/s/1vYYKX9BdlQIHY-Y7E9n5nA?pwd=1234)(password:1234) or [GoogleDrive](https://drive.google.com/file/d/1qCXQkiJ3fAHtmKi6U0CnXTzgiGKRfxIC/view), or yourself weight. And put it in `./weights` folder of visualization code.
2. Note that the input path must be absolute path!
3. The command of visualization is as following:
`python train_net.py --config-file configs/faster_rcnn_R50_bdd100k.yaml --input ABSOLUTE_PATH/visual_img_night/*.jpg --output ./visual_results  --opts MODEL.WEIGHT ./weights/bdd100k_model.pth`

If you have any questions, please feel free to contact me.

**Comment by yanguo-lucky** [comment]
> @yanguo-lucky 您好，感谢您对我们工作的关注。我已将可视化代码上传到此链接： [网盘](https://pan.baidu.com/s/1ui4t7kf2otWXh6kKdViSzQ)（密码：6666）或[GoogleDrive](https://drive.google.com/drive/folders/1g5WsGAL0zduyXJyNucZnltyWcMSRoyHm?usp=drive_link)
> 
> 1. [您可以从百度云](https://pan.baidu.com/s/1vYYKX9BdlQIHY-Y7E9n5nA?pwd=1234)（密码：1234）或[GoogleDrive](https://drive.google.com/drive/folders/1ynapIcAm5subozk0QNzrPWHwWj_xpGle?usp=drive_link)下载我们的权限重（48.8 AP），或者您自己的权限重。将其放在`./weights`可视化代码文件夹中。
> 2. 注意输入路径一定是绝对路径！
> 3. 可视化命令如下：
>    `python train_net.py --config-file configs/faster_rcnn_R50_bdd100k.yaml --input ABSOLUTE_PATH/visual_img_night/*.jpg --output ./visual_results  --opts MODEL.WEIGHT ./weights/bdd100k_model.pth`
> 
> 如果您有任何疑问，请随时联系我。

Thank you very much. I've already tested out the visualization results. However, the weight link you provided seems to be a label file. I downloaded the weights using the link in the README file. Thanks again!

**Comment by yanguo-lucky** [comment]
> @yanguo-lucky 您好，感谢您对我们工作的关注。我已将可视化代码上传到此链接： [网盘](https://pan.baidu.com/s/1ui4t7kf2otWXh6kKdViSzQ)（密码：6666）或[GoogleDrive](https://drive.google.com/drive/folders/1g5WsGAL0zduyXJyNucZnltyWcMSRoyHm?usp=drive_link)
> 
> 1. [您可以从百度云](https://pan.baidu.com/s/1vYYKX9BdlQIHY-Y7E9n5nA?pwd=1234)（密码：1234）或[GoogleDrive](https://drive.google.com/drive/folders/1ynapIcAm5subozk0QNzrPWHwWj_xpGle?usp=drive_link)下载我们的权限重（48.8 AP），或者您自己的权限重。将其放在`./weights`可视化代码文件夹中。
> 2. 注意输入路径一定是绝对路径！
> 3. 可视化命令如下：
>    `python train_net.py --config-file configs/faster_rcnn_R50_bdd100k.yaml --input ABSOLUTE_PATH/visual_img_night/*.jpg --output ./visual_results  --opts MODEL.WEIGHT ./weights/bdd100k_model.pth`
> 
> 如果您有任何疑问，请随时联系我。

Thank you very much. I've already tested out the visualization results according to the steps you provided. However, it seems that the weight link you gave is for the label file. I downloaded the weights using the link in the README file. Thanks again!

**Comment by zhangyin1996** [comment]
> > @yanguo-lucky 您好，感谢您对我们工作的关注。我已将可视化代码上传到此链接： [网盘](https://pan.baidu.com/s/1ui4t7kf2otWXh6kKdViSzQ)（密码：6666）或[GoogleDrive](https://drive.google.com/drive/folders/1g5WsGAL0zduyXJyNucZnltyWcMSRoyHm?usp=drive_link)
> > 
> > 1. [您可以从百度云](https://pan.baidu.com/s/1vYYKX9BdlQIHY-Y7E9n5nA?pwd=1234)（密码：1234）或[GoogleDrive](https://drive.google.com/drive/folders/1ynapIcAm5subozk0QNzrPWHwWj_xpGle?usp=drive_link)下载我们的权限重（48.8 AP），或者您自己的权限重。将其放在`./weights`可视化代码文件夹中。
> > 2. 注意输入路径一定是绝对路径！
> > 3. 可视化命令如下：
> >    `python train_net.py --config-file configs/faster_rcnn_R50_bdd100k.yaml --input ABSOLUTE_PATH/visual_img_night/*.jpg --output ./visual_results  --opts MODEL.WEIGHT ./weights/bdd100k_model.pth`
> > 
> > 如果您有任何疑问，请随时联系我。
> 
> Thank you very much. I've already tested out the visualization results according to the steps you provided. However, it seems that the weight link you gave is for the label file. I downloaded the weights using the link in the README file. Thanks again!

Thanks for the reminder, I have updated the link. Also, I will close this issue, if you have any questions, you can reopen it
